with
    src_Sugar_contacts as(
        select *
        from {{ source('Sugar', 'contacts') }}
    )

select
    {{ field_clean('"date_entered"') }} as date_entered
    ,{{ field_clean('"primary_address_street"') }} as primary_address_street
    ,{{ field_clean('"primary_address_city"') }} as primary_address_city
    ,{{ field_clean('"primary_address_state"') }} as primary_address_state
    ,{{ field_clean('"primary_address_postalcode"') }} as primary_address_postalcode
    ,{{ field_clean('"primary_address_country"') }} as primary_address_country
    ,{{ field_clean('"subdivision_c"') }} as subdivision_c
    ,{{ field_clean('"availableinternetphoneoption_c"') }} as availableinternetphoneoption_c
    ,{{ field_clean('"availableelectricoption_c"') }} as availableelectricoption_c
    ,{{ field_clean('"availablegasoption_c"') }} as availablegasoption_c
    ,{{ field_clean('"availablewatertrashoptions_c"') }} as availablewatertrashoptions_c
    ,{{ field_clean('"tv_options_c"') }} as tv_options_c
    ,{{ field_clean('"internet_phone_options_c"') }} as internet_phone_options_c
    ,{{ field_clean('"availabletvoptions_c"') }} as availabletvoptions_c
    ,{{ field_clean('"electric_options_c"') }} as electric_options_c
    ,{{ field_clean('"gas_options_c"') }} as gas_options_c
    ,{{ field_clean('"water_trash_options_c"') }} as water_trash_options_c
    ,{{ field_clean('"sewer_options_c"') }} as sewer_options_c
    ,{{ field_clean('"trash_options_c"') }} as trash_options_c

    -- so Eric Minish can look for Reshop customers
    ,{{ field_clean('"name"') }} as name
    ,{{ field_clean('"rent_buy_c"') }} as rent_buy_c

from src_Sugar_contacts

/*
    ,{{ field_clean('"primary_address_street_2"') }} as primary_address_street_2
    ,{{ field_clean('"primary_address_street_3"') }} as primary_address_street_3
    ,{{ field_clean('"alt_address_street"') }} as alt_address_street
    ,{{ field_clean('"alt_address_street_2"') }} as alt_address_street_2
    ,{{ field_clean('"alt_address_street_3"') }} as alt_address_street_3
    ,{{ field_clean('"alt_address_city"') }} as alt_address_city
    ,{{ field_clean('"alt_address_state"') }} as alt_address_state
    ,{{ field_clean('"alt_address_postalcode"') }} as alt_address_postalcode
    ,{{ field_clean('"alt_address_country"') }} as alt_address_country
    ,{{ field_clean('"otherelectricprovider_c"') }} as otherelectricprovider_c
    ,{{ field_clean('"othergasprovider_c"') }} as othergasprovider_c
    ,{{ field_clean('"wirelessreceivers_c"') }} as wirelessreceivers_c
    ,{{ field_clean('"internetmodem_c"') }} as internetmodem_c
    ,{{ field_clean('"internetrouter_c"') }} as internetrouter_c
    ,{{ field_clean('"othertvprovider_c"') }} as othertvprovider_c
    ,{{ field_clean('"trashcomments_c"') }} as trashcomments_c
    ,{{ field_clean('"googlemaps_c"') }} as googlemaps_c
    ,{{ field_clean('"securityproviderorderform_c"') }} as securityproviderorderform_c
    ,{{ field_clean('"electricprovider_c"') }} as electricprovider_c
    ,{{ field_clean('"gasprovider_c"') }} as gasprovider_c
    ,{{ field_clean('"waterprovider_c"') }} as waterprovider_c
    ,{{ field_clean('"internetproviderorderform_c"') }} as internetproviderorderform_c
    ,{{ field_clean('"phoneproviderorderform_c"') }} as phoneproviderorderform_c
    ,{{ field_clean('"water_setup_process_c"') }} as water_setup_process_c
    ,{{ field_clean('"gas_setup_process_c"') }} as gas_setup_process_c
    ,{{ field_clean('"electric_setup_process_c"') }} as electric_setup_process_c
    ,{{ field_clean('"sewer_provider_c"') }} as sewer_provider_c
    ,{{ field_clean('"id"') }} as id
    ,{{ field_clean('"date_modified"') }} as date_modified
    ,{{ field_clean('"modified_user_id"') }} as modified_user_id
    ,{{ field_clean('"modified_by_name"') }} as modified_by_name
    ,{{ field_clean('"created_by"') }} as created_by
    ,{{ field_clean('"created_by_name"') }} as created_by_name
    ,{{ field_clean('"description"') }} as description
    ,{{ field_clean('"deleted"') }} as deleted
    ,{{ field_clean('"salutation"') }} as salutation
    ,{{ field_clean('"first_name"') }} as first_name
    ,{{ field_clean('"last_name"') }} as last_name
    ,{{ field_clean('"full_name"') }} as full_name
    ,{{ field_clean('"title"') }} as title
    ,{{ field_clean('"facebook"') }} as facebook
    ,{{ field_clean('"twitter"') }} as twitter
    ,{{ field_clean('"googleplus"') }} as googleplus
    ,{{ field_clean('"department"') }} as department
    ,{{ field_clean('"do_not_call"') }} as do_not_call
    ,{{ field_clean('"phone_home"') }} as phone_home
    ,{{ field_clean('"phone_mobile"') }} as phone_mobile
    ,{{ field_clean('"phone_work"') }} as phone_work
    ,{{ field_clean('"phone_other"') }} as phone_other
    ,{{ field_clean('"phone_fax"') }} as phone_fax
    ,{{ field_clean('"assistant"') }} as assistant
    ,{{ field_clean('"assistant_phone"') }} as assistant_phone
    ,{{ field_clean('"picture"') }} as picture
    ,{{ field_clean('"lead_source"') }} as lead_source
    ,{{ field_clean('"account_name"') }} as account_name
    ,{{ field_clean('"account_id"') }} as account_id
    ,{{ field_clean('"dnb_principal_id"') }} as dnb_principal_id
    ,{{ field_clean('"opportunity_role_fields"') }} as opportunity_role_fields
    ,{{ field_clean('"opportunity_role_id"') }} as opportunity_role_id
    ,{{ field_clean('"opportunity_role"') }} as opportunity_role
    ,{{ field_clean('"reports_to_id"') }} as reports_to_id
    ,{{ field_clean('"report_to_name"') }} as report_to_name
    ,{{ field_clean('"birthdate"') }} as birthdate
    ,{{ field_clean('"portal_name"') }} as portal_name
    ,{{ field_clean('"portal_active"') }} as portal_active
    ,{{ field_clean('"portal_password"') }} as portal_password
    ,{{ field_clean('"portal_password1"') }} as portal_password1
    ,{{ field_clean('"portal_app"') }} as portal_app
    ,{{ field_clean('"portal_user_company_name"') }} as portal_user_company_name
    ,{{ field_clean('"preferred_language"') }} as preferred_language
    ,{{ field_clean('"cookie_consent"') }} as cookie_consent
    ,{{ field_clean('"cookie_consent_received_on"') }} as cookie_consent_received_on
    ,{{ field_clean('"business_center_name"') }} as business_center_name
    ,{{ field_clean('"business_center_id"') }} as business_center_id
    ,{{ field_clean('"dp_business_purpose"') }} as dp_business_purpose
    ,{{ field_clean('"dp_consent_last_updated"') }} as dp_consent_last_updated
    ,{{ field_clean('"campaign_id"') }} as campaign_id
    ,{{ field_clean('"campaign_name"') }} as campaign_name
    ,{{ field_clean('"c_accept_status_fields"') }} as c_accept_status_fields
    ,{{ field_clean('"m_accept_status_fields"') }} as m_accept_status_fields
    ,{{ field_clean('"accept_status_id"') }} as accept_status_id
    ,{{ field_clean('"accept_status_name"') }} as accept_status_name
    ,{{ field_clean('"accept_status_calls"') }} as accept_status_calls
    ,{{ field_clean('"accept_status_meetings"') }} as accept_status_meetings
    ,{{ field_clean('"accept_status_messages"') }} as accept_status_messages
    ,{{ field_clean('"hint_account_size"') }} as hint_account_size
    ,{{ field_clean('"hint_account_industry"') }} as hint_account_industry
    ,{{ field_clean('"hint_account_location"') }} as hint_account_location
    ,{{ field_clean('"hint_account_description"') }} as hint_account_description
    ,{{ field_clean('"hint_job_2"') }} as hint_job_2
    ,{{ field_clean('"hint_education"') }} as hint_education
    ,{{ field_clean('"hint_education_2"') }} as hint_education_2
    ,{{ field_clean('"hint_facebook"') }} as hint_facebook
    ,{{ field_clean('"hint_twitter"') }} as hint_twitter
    ,{{ field_clean('"hint_industry_tags"') }} as hint_industry_tags
    ,{{ field_clean('"hint_account_founded_year"') }} as hint_account_founded_year
    ,{{ field_clean('"hint_account_facebook_handle"') }} as hint_account_facebook_handle
    ,{{ field_clean('"hint_account_twitter_handle"') }} as hint_account_twitter_handle
    ,{{ field_clean('"hint_account_logo"') }} as hint_account_logo
    ,{{ field_clean('"hint_contact_pic"') }} as hint_contact_pic
    ,{{ field_clean('"hint_photo"') }} as hint_photo
    ,{{ field_clean('"hint_phone_1"') }} as hint_phone_1
    ,{{ field_clean('"hint_phone_2"') }} as hint_phone_2
    ,{{ field_clean('"hint_account_website"') }} as hint_account_website
    ,{{ field_clean('"hint_account_naics_code_lbl"') }} as hint_account_naics_code_lbl
    ,{{ field_clean('"hint_account_sic_code_label"') }} as hint_account_sic_code_label
    ,{{ field_clean('"hint_account_fiscal_year_end"') }} as hint_account_fiscal_year_end
    ,{{ field_clean('"hint_account_annual_revenue"') }} as hint_account_annual_revenue
    ,{{ field_clean('"sync_contact"') }} as sync_contact
    ,{{ field_clean('"market_interest_prediction_score"') }} as market_interest_prediction_score
    ,{{ field_clean('"market_score"') }} as market_score
    ,{{ field_clean('"mkto_sync"') }} as mkto_sync
    ,{{ field_clean('"mkto_id"') }} as mkto_id
    ,{{ field_clean('"mkto_lead_score"') }} as mkto_lead_score
    ,{{ field_clean('"entry_source"') }} as entry_source
    ,{{ field_clean('"site_user_id"') }} as site_user_id
    ,{{ field_clean('"following"') }} as follow
    ,{{ field_clean('"my_favorite"') }} as my_favorite
    ,{{ field_clean('"tag"') }} as tag
    ,{{ field_clean('"commentlog"') }} as commentlog
    ,{{ field_clean('"locked_fields"') }} as locked_fields
    ,{{ field_clean('"sync_key"') }} as sync_key
    ,{{ field_clean('"assigned_user_id"') }} as assigned_user_id
    ,{{ field_clean('"assigned_user_name"') }} as assigned_user_name
    ,{{ field_clean('"team_id"') }} as team_id
    ,{{ field_clean('"team_set_id"') }} as team_set_id
    ,{{ field_clean('"acl_team_set_id"') }} as acl_team_set_id
    ,{{ field_clean('"team_name"') }} as team_name
    ,{{ field_clean('"email"') }} as email
    ,{{ field_clean('"client_told_c"') }} as client_told_c
    ,{{ field_clean('"referrer_email_c"') }} as referrer_email_c
    ,{{ field_clean('"web_submission_c"') }} as web_submission_c
    ,{{ field_clean('"move_in_date_c"') }} as move_in_date_c
    ,{{ field_clean('"inspection_date_c"') }} as inspection_date_c
    ,{{ field_clean('"client_present_c"') }} as client_present_c
    ,{{ field_clean('"epi_personal_information_contacts_1_name"') }} as epi_personal_information_contacts_1_name
    ,{{ field_clean('"epi_personal_information_contacts_1epi_personal_information_ida"') }} as epi_personal_information_contacts_1epi_personal_information_ida
    ,{{ field_clean('"comments_c"') }} as comments_c
    ,{{ field_clean('"spanish_c"') }} as spanish_c
    ,{{ field_clean('"electricstartdate_c"') }} as electricstartdate_c
    ,{{ field_clean('"waterstatusorderform_c"') }} as waterstatusorderform_c
    ,{{ field_clean('"wateractivationdateorderform_c"') }} as wateractivationdateorderform_c
    ,{{ field_clean('"current_water_c"') }} as current_water_c
    ,{{ field_clean('"current_trash_c"') }} as current_trash_c
    ,{{ field_clean('"current_gas_c"') }} as current_gas_c
    ,{{ field_clean('"gasstatusorderform_c"') }} as gasstatusorderform_c
    ,{{ field_clean('"gasrequestedactivationdate_c"') }} as gasrequestedactivationdate_c
    ,{{ field_clean('"gascommentsorderform_c"') }} as gascommentsorderform_c
    ,{{ field_clean('"watercommentsorderform_c"') }} as watercommentsorderform_c
    ,{{ field_clean('"trashrequestedactivationdate_c"') }} as trashrequestedactivationdate_c
    ,{{ field_clean('"tvdvr_c"') }} as tvdvr_c
    ,{{ field_clean('"tvrequestedinstalldate_c"') }} as tvrequestedinstalldate_c
    ,{{ field_clean('"internetrequestedinstalldate_c"') }} as internetrequestedinstalldate_c
    ,{{ field_clean('"phoneplanorderform_c"') }} as phoneplanorderform_c
    ,{{ field_clean('"phonestatusorderform_c"') }} as phonestatusorderform_c
    ,{{ field_clean('"phonerequestedinstalldateord_c"') }} as phonerequestedinstalldateord_c
    ,{{ field_clean('"phonecommentsorderform_c"') }} as phonecommentsorderform_c
    ,{{ field_clean('"securitytype_c"') }} as securitytype_c
    ,{{ field_clean('"securitymmrorderform_c"') }} as securitymmrorderform_c
    ,{{ field_clean('"securityinstallationcost_c"') }} as securityinstallationcost_c
    ,{{ field_clean('"securitypackage_c"') }} as securitypackage_c
    ,{{ field_clean('"securitycommentsorderform_c"') }} as securitycommentsorderform_c
    ,{{ field_clean('"internetotherprovider_c"') }} as internetotherprovider_c
    ,{{ field_clean('"otherphoneprovider_c"') }} as otherphoneprovider_c
    ,{{ field_clean('"squarecowmooversorderform_c"') }} as squarecowmooversorderform_c
    ,{{ field_clean('"trashproviderorderform_c"') }} as trashproviderorderform_c
    ,{{ field_clean('"whiteknightpestcontrolorder_c"') }} as whiteknightpestcontrolorder_c
    ,{{ field_clean('"mrrekeyorderform_c"') }} as mrrekeyorderform_c
    ,{{ field_clean('"delicatemoving_c"') }} as delicatemoving_c
    ,{{ field_clean('"adt_c"') }} as adt_c
    ,{{ field_clean('"middle_name_c"') }} as middle_name_c
    ,{{ field_clean('"electriccommentsorderform_c"') }} as electriccommentsorderform_c
    ,{{ field_clean('"other_options_c"') }} as other_options_c
    ,{{ field_clean('"referralname_c"') }} as referralname_c
    ,{{ field_clean('"numberoftvsorderform_c"') }} as numberoftvsorderform_c
    ,{{ field_clean('"email_2_c"') }} as email_2_c
    ,{{ field_clean('"numberoflines_c"') }} as numberoflines_c
    ,{{ field_clean('"qafudate_c"') }} as qafudate_c
    ,{{ field_clean('"dateassignedtooe_c"') }} as dateassignedtooe_c
    ,{{ field_clean('"status_c"') }} as status_c
    ,{{ field_clean('"typeofphone_c"') }} as typeofphone_c
    ,{{ field_clean('"agreedtotext_c"') }} as agreedtotext_c
    ,{{ field_clean('"consultant_qa_date_c"') }} as consultant_qa_date_c
    ,{{ field_clean('"secondary_install_date_c"') }} as secondary_install_date_c
    ,{{ field_clean('"int_secondary_install_date_c"') }} as int_secondary_install_date_c
    ,{{ field_clean('"rc360_referrer_contacts_name"') }} as rc360_referrer_contacts_name
    ,{{ field_clean('"rc360_referrer_contactsrc360_referrer_ida"') }} as rc360_referrer_contactsrc360_referrer_ida
    ,{{ field_clean('"rc360_teams_contacts_name"') }} as rc360_teams_contacts_name
    ,{{ field_clean('"rc360_teams_contactsrc360_teams_ida"') }} as rc360_teams_contactsrc360_teams_ida
    ,{{ field_clean('"clientstatus_c"') }} as clientstatus_c
    ,{{ field_clean('"referral_company_c"') }} as referral_company_c
    ,{{ field_clean('"referred_by_c"') }} as referred_by_c
    ,{{ field_clean('"mobility_pricing_c"') }} as mobility_pricing_c
    ,{{ field_clean('"other_referral_services_c"') }} as other_referral_services_c
    ,{{ field_clean('"cancellations_c"') }} as cancellations_c
    ,{{ field_clean('"cancellation_reason_c"') }} as cancellation_reason_c
    ,{{ field_clean('"bd360_bd_rep_contacts_name"') }} as bd360_bd_rep_contacts_name
    ,{{ field_clean('"bd360_bd_rep_contactsbd360_bd_rep_ida"') }} as bd360_bd_rep_contactsbd360_bd_rep_ida
    ,{{ field_clean('"qli_total_revenue_c"') }} as qli_total_revenue_c
    ,{{ field_clean('"tv_am_or_pm_c"') }} as tv_am_or_pm_c
    ,{{ field_clean('"internet_am_or_pm_c"') }} as internet_am_or_pm_c
    ,{{ field_clean('"electricstatus_c"') }} as electricstatus_c
    ,{{ field_clean('"gas_username_c"') }} as gas_username_c
    ,{{ field_clean('"gas_disconnect_date_c"') }} as gas_disconnect_date_c
    ,{{ field_clean('"gas_password_c"') }} as gas_password_c
    ,{{ field_clean('"internet_speed_c"') }} as internet_speed_c
    ,{{ field_clean('"statusdetail_c"') }} as statusdetail_c
    ,{{ field_clean('"telecomeactivation_c"') }} as telecomeactivation_c
    ,{{ field_clean('"telecomofferprice_c"') }} as telecomofferprice_c
    ,{{ field_clean('"why_no_service_c"') }} as why_no_service_c
    ,{{ field_clean('"atx_firefighter_moving_c"') }} as atx_firefighter_moving_c
    ,{{ field_clean('"adsorderform_c"') }} as adsorderform_c
    ,{{ field_clean('"c1_insurance_c"') }} as c1_insurance_c
    ,{{ field_clean('"firefightings_finest_moving_c"') }} as firefightings_finest_moving_c
    ,{{ field_clean('"vivint_c"') }} as vivint_c
    ,{{ field_clean('"coaching_opportunity_c"') }} as coaching_opportunity_c
    ,{{ field_clean('"sewer_activation_date_c"') }} as sewer_activation_date_c
    ,{{ field_clean('"sewer_comments_c"') }} as sewer_comments_c
    ,{{ field_clean('"security_rep_c"') }} as security_rep_c
    ,{{ field_clean('"transferredcalldate_c"') }} as transferredcalldate_c
    ,{{ field_clean('"qualifier_c"') }} as qualifier_c
    ,{{ field_clean('"securityrequesteddateorderfo_c"') }} as securityrequesteddateorderfo_c
    ,{{ field_clean('"tvprovider_c"') }} as tvprovider_c
    ,{{ field_clean('"tv_status_c"') }} as tv_status_c
    ,{{ field_clean('"internet_status_c"') }} as internet_status_c
    ,{{ field_clean('"bt360_teams_contacts_1_name"') }} as bt360_teams_contacts_1_name
    ,{{ field_clean('"bt360_teams_contacts_1bt360_teams_ida"') }} as bt360_teams_contacts_1bt360_teams_ida
    ,{{ field_clean('"secondary_referrer_email_c"') }} as secondary_referrer_email_c
    ,{{ field_clean('"phone_secondary_c"') }} as phone_secondary_c
    ,{{ field_clean('"static_shield_c"') }} as static_shield_c
    ,{{ field_clean('"lendid_home_loans_c"') }} as lendid_home_loans_c
    ,{{ field_clean('"text_template_c"') }} as text_template_c
    ,{{ field_clean('"click_to_dial_c"') }} as click_to_dial_c
    ,{{ field_clean('"electric_rate_c"') }} as electric_rate_c
    ,{{ field_clean('"internet_rate_c"') }} as internet_rate_c
    ,{{ field_clean('"phone_rate_c"') }} as phone_rate_c
    ,{{ field_clean('"sec_rate_c"') }} as sec_rate_c
    ,{{ field_clean('"current_sewer_c"') }} as current_sewer_c
    ,{{ field_clean('"tv_rate_c"') }} as tv_rate_c
    ,{{ field_clean('"research_completed_c"') }} as research_completed_c
    ,{{ field_clean('"closing_date_c"') }} as closing_date_c
    ,{{ field_clean('"onit_water_requested_date_c"') }} as onit_water_requested_date_c
    ,{{ field_clean('"onit_water_requested_time_c"') }} as onit_water_requested_time_c
    ,{{ field_clean('"culligan_ultrapure_c"') }} as culligan_ultrapure_c
    ,{{ field_clean('"oncall_home_services_c"') }} as oncall_home_services_c
    ,{{ field_clean('"punchlist_c"') }} as punchlist_c
    ,{{ field_clean('"tvcommentsorderform_c"') }} as tvcommentsorderform_c
    ,{{ field_clean('"internetcommentsorderform_c"') }} as internetcommentsorderform_c
    ,{{ field_clean('"utilities_disconnect_date_c"') }} as utilities_disconnect_date_c
    ,{{ field_clean('"disconnect_date_telecom_c"') }} as disconnect_date_telecom_c
    ,{{ field_clean('"brinks_c"') }} as brinks_c
    ,{{ field_clean('"home_warranty_inc_c"') }} as home_warranty_inc_c
    ,{{ field_clean('"saved_sale_c"') }} as saved_sale_c
    ,{{ field_clean('"calendly_link_text_c"') }} as calendly_link_text_c
    ,{{ field_clean('"calendly_link_c"') }} as calendly_link_c
    ,{{ field_clean('"new_action_c"') }} as new_action_c
    ,{{ field_clean('"saved_sale_date_c"') }} as saved_sale_date_c
    ,{{ field_clean('"sewer_status_c"') }} as sewer_status_c
    ,{{ field_clean('"trash_status_c"') }} as trash_status_c
    ,{{ field_clean('"available_sewer_option_c"') }} as available_sewer_option_c
    ,{{ field_clean('"available_trash_option_c"') }} as available_trash_option_c
    ,{{ field_clean('"onit_water_c"') }} as onit_water_c
    ,{{ field_clean('"electricterm_c"') }} as electricterm_c
    ,{{ field_clean('"electricrate_c"') }} as electricrate_c
    ,{{ field_clean('"opportunity_create_silent_button"') }} as opportunity_create_silent_button
    ,{{ field_clean('"asap_c"') }} as asap_c
    ,{{ field_clean('"testimonial_date_c"') }} as testimonial_date_c
    ,{{ field_clean('"testimonial_c"') }} as testimonial_c
    ,{{ field_clean('"eighty_eight_doors_c"') }} as eighty_eight_doors_c
    ,{{ field_clean('"tvpinnumberorderform_c"') }} as tvpinnumberorderform_c
    ,{{ field_clean('"internetpinnumberorderform_c"') }} as internetpinnumberorderform_c
    ,{{ field_clean('"tvsecurityanswerorderform_c"') }} as tvsecurityanswerorderform_c
    ,{{ field_clean('"internetsecurityanswerorders_c"') }} as internetsecurityanswerorders_c
    ,{{ field_clean('"buyers_name_c"') }} as buyers_name_c
    ,{{ field_clean('"seller_name_c"') }} as seller_name_c
    ,{{ field_clean('"goosehead_insurance_c"') }} as goosehead_insurance_c
    ,{{ field_clean('"new_address_city_c"') }} as new_address_city_c
    ,{{ field_clean('"new_address_country_c"') }} as new_address_country_c
    ,{{ field_clean('"new_address_postalcode_c"') }} as new_address_postalcode_c
    ,{{ field_clean('"new_address_street_c"') }} as new_address_street_c
    ,{{ field_clean('"new_address_state_c"') }} as new_address_state_c
    ,{{ field_clean('"current_address_country_c"') }} as current_address_country_c
    ,{{ field_clean('"create_reshop_c"') }} as create_reshop_c
    ,{{ field_clean('"lastcallnote_c"') }} as lastcallnote_c
    ,{{ field_clean('"elite_star_movers_c"') }} as elite_star_movers_c
    ,{{ field_clean('"createtask_c"') }} as createtask_c
    ,{{ field_clean('"alpha_omega_insurance_c"') }} as alpha_omega_insurance_c
    ,{{ field_clean('"send_rse_temp_c"') }} as send_rse_temp_c
    ,{{ field_clean('"bd_rep_c"') }} as bd_rep_c
    ,{{ field_clean('"tvplan_c"') }} as tvplan_c
    ,{{ field_clean('"voicemail_templates_c"') }} as voicemail_templates_c
    ,{{ field_clean('"freedom_solar_c"') }} as freedom_solar_c
    ,{{ field_clean('"base_rate"') }} as base_rate
    ,{{ field_clean('"currency_id"') }} as currency_id
*/