version: 2

models:
  - name: dim_agent
    description: Users who are agents.  One row per agent.  In other words, they are either TC users who have the role of 'role-agent', or they are agents assigned to Salesforce leads
    columns:
      - name: agent_pk
        description: agent primary key.  Assigned by data warehouse.

      - name: user_id
        description: unique identifier for the user. Assigned by TC app.

      - name: agent_name
        description: full name of the agent

      - name: agent_email
        description: email of the agent

      - name: tc_created_date
        description: the date the TC user record was created

      - name: lead_created_date
        description: the date the lead record was created

      - name: tc_agent_flag
        description: 1 = is a TC Agent, 0 = not a TC Agent

      - name: lead_agent_flag
        description: 1 = is a lead Agent, 0 = not a lead Agent

      - name: agent_type
        description: whether the agent is 'TC', 'Lead', or 'TC and Lead'

  - name: dim_contact
    description: One row per TC contact.  These are the people associated with a transaction who aren't a member.
    columns:
      - name: contact_pk
        description: contact primary key.  Assigned by data warehouse

      - name: contact_id
        description: unique identifier for the contact.  Assigned by TC app

      - name: role_name
        description: the role of the contact as assigned in TC app

      - name: party_name
        description: two options - 'buyer' or 'seller'

      - name: side_id
        description: numeric value associated with party_name

      - name: email
        description: contact email

      - name: last_name
        description: last name of the contact

      - name: first_name
        description: first name of the contact

      - name: transaction_id
        description: unique identifier for the transaction

  - name: dim_date
    description: one row per date
    columns:
      - name: date_pk
        description: date primary key.  Assigned by data warehouse

      - name: date_id
        description: unique identifier of the date.  Assigned by data warehouse.  The number is made up yyy-mm-dd

      - name: year
        description: date year in digits

      - name: month
        description: date month in digits

      - name: month_name
        description: date month in three letters (Jan, Feb, Mar...)

      - name: day_of_mon
        description: day of month (1-31)

      - name: day_of_week
        description: day of week (1-7)

      - name: week_of_year
        description: week of year (1-52)

      - name: day_of_year
        description: day of year (1-365)

  - name: dim_lead
    description: one row per Salesforce lead
    columns:
      - name: lead_pk
        description: lead primary key.  Assigned by data warehouse

      - name: lead_id
        description: unique identifier of the lead.  Assigned by Salesforce

      - name: first_name
        description: first name of lead

      - name: last_name
        description: last name of lead

      - name: name
        description: full name of lead

      - name: company
        description: the source of the lead

      - name: street
        description: lead street address

      - name: city
        description: lead city address

      - name: state
        description: lead state address

      - name: zip
        description: lead zip address

      - name: country
        description: lead country address

      - name: full_address
        description: combined street, city, state, country

      - name: phone
        description: lead phone

      - name: email
        description: lead email

      - name: lead_source
        description: source of lead

      - name: lead_created_date
        description: date when the lead record was created

      - name: agent_name
        description: name of the lead's agent

      - name: agent_email
        description: email of the lead's agent

      - name: electricity
        description: where the lead signed up for electricity utility

      - name: sewer
        description: where the lead signed up for sewer utility

      - name: trash
        description: where the lead signed up for trash utility

      - name: water
        description: where the lead signed up for water utility

      - name: gas
        description: where the lead signed up for gas utility

      - name: internet
        description: where the lead signed up for internet

      - name: account_name
        description: the account of the lead

      - name: account_owner
        description: the owner of the lead's account

  - name: dim_line_item
    description: one row per TC order line item
    columns:
      - name: line_item_pk
        description: line item primary key.  Assigned by data warehouse

      - name: line_item_id
        description: line item unique identifier.  Assigned by TC app

      - name: status
        description: (in progress, complete, withdrawn, active, closed, ...)

      - name: description
        description: (transaction coordination fee, listing coordination fee, ...)

      - name: agent_pays
        description: $ amount the agent pays

      - name: office_pays
        description: $ amount the office pays

      - name: total_fees
        description: $ agent pays + $ office pays

      - name: due_date
        description: line item due date

      - name: paid
        description: (yes, no)

      - name: tc_paid
        description: (yes, no)

      - name: cancelled_date
        description: date the line item was cancelled

      - name: created_date
        description: date the line item was created

      - name: last_sync
        description: the last time Fivetran pulled data from the TC app into dim_line_item

  - name: dim_member_contact
    description: one row per transaction per member or contact
    columns:
      - name: member_contact_pk
        description: member_contact primary key.  Assigned by data warehouse

      - name: member_contact_id
        description: member or contact unique id.  Assigned by TC app
        
      - name: transaction_id
        description: transaction unique id.  Assigned by TC app
        
      - name: member_or_contact
        description: whether the record is for a member or for a contact (member, contact)

      - name: first_name
        description: member or contact first name

      - name: last_name
        description: member or contact last name

      - name: phone
        description: member or contact phone

      - name: email
        description: member or contact email

      - name: role_id
        description: an integer representing the role name (1-22)

      - name: role_name
        description: the member or contact role (buyer agent, seller agent, loan processor, ...)

      - name: party_id
        description: an integer representing the party name (1-2)

      - name: party_name
        description: (buyer, seller)

      - name: member_flag
        description: a 1 or 0 representing whether the row represents a member

      - name: contact_flag
        description: a 1 or 0 representing whether the row represents a contact

      - name: utility_opt_in_status
        description: whether the contact or lead has opted in or not to utilites (IN, OUT)


