version: 2

sources:
  # name per Fivetran Transform requirements
  # fivetran_connecter_name_destination_schema
  - name: gcp_prod_gcp_prod_prod  
  # - name: tc
    description: "Transactly data sources"
    database: fivetran
    schema: gcp_prod_prod
    tables:
      - name: address
      - name: agent_acct_credentials
      - name: agent_subscription_tier
      - name: contact
      - name: contract
      - name: line_item
      - name: member
      - name: offer_group
      - name: office
      - name: office_user
      - name: party
      - name: role
      - name: task
      - name: task_status
      - name: tc_order
      - name: transaction
      - name: transaction_role
      - name: transaction_status
      - name: transaction_transactly_vendor
      - name: transaction_transactly_vendor_member_notified
      - name: transactly_vendor
      - name: user
      - name: user_agent_subscription_tier
      - name: user_role
      - name: user_subscription
      - name: user_transactly_vendor_opt_out
      - name: user_vendor

  - name: mls
    description: "mls data sources"
    database: airbyte
    schema: postgresql
    tables:
      - name: ags
        identifier: ags

      - name: listings
        identifier: listings

      - name: ofs
        identifier: ofs

  - name: hs
    description: "hubspot data sources"
    database: hubspot
    schema: v2_daily
    tables:
      - name: object_properties
        identifier: object_properties

      - name: owners
        identifier: owners

      - name: pipeline_stages
        identifier: pipeline_stages

      - name: pipelines
        identifier: pipelines

  - name: Sugar
    description: "SugarCRM data sources"
    database: Skyvia
    schema: sugarcrm
    tables:
      - name: accounts
        identifier: '"Accounts"'

      - name: contacts
        identifier: '"Contacts"'

      - name: opportunities
        identifier: '"Opportunities"'

      - name: rc360_referrer
        identifier: '"RC360_Referrer"'

      - name: revenuelineitems
        identifier: '"RevenueLineItems"'

  - name: salesforce_salesforce
    description: "Salesforce data sources"
    database: fivetran
    schema: salesforce
    tables:
      - name: account
        identifier: account

      - name: agscmi_activity_c
        identifier: agscmi_activity_c

      - name: contact
        identifier: contact

      - name: lead
        identifier: lead

      - name: opportunity
        identifier: opportunity

      - name: opportunity_line_item
        identifier: opportunity_line_item

      - name: partner_lead_c
        identifier: partner_lead_c

      - name: partner_payout_c
        identifier: partner_payout_c

      - name: product_2
        identifier: product_2

      - name: twilio_sf_message_c
        identifier: twilio_sf_message_c

      - name: user
        identifier: user

      - name: vendor_payout_c
        identifier: vendor_payout_c

      - name: record_type
        identifier: record_type