version: 2

sources:
  - name: tc
    description: "Transactly data sources"
    database: fivetran
    schema: transactly_app_production_rec_accounts
    tables:
      - name: address
        identifier: address

      - name: agent_subscription_tier
        identifier: agent_subscription_tier

      - name: contact
        identifier: contact

      - name: contract
        identifier: contract

      - name: line_item
        identifier: line_item

      - name: member
        identifier: member

      - name: offer_group
        identifier: offer_group

      - name: office
        identifier: office

      - name: office_user
        identifier: office_user

      - name: order
        identifier: tc_order

      - name: party
        identifier: party

      - name: role
        identifier: role

      - name: transaction
        identifier: transaction

      - name: transaction_role
        identifier: transaction_role

      - name: transaction_status
        identifier: transaction_status

      - name: transaction_transactly_vendor
        identifier: transaction_transactly_vendor

      - name: transaction_transactly_vendor_member_notified
        identifier: transaction_transactly_vendor_member_notified

      - name: transactly_vendor
        identifier: transactly_vendor

      - name: user
        identifier: user

      - name: user_agent_subscription_tier
        identifier: user_agent_subscription_tier

      - name: user_role
        identifier: user_role

      - name: user_subscription
        identifier: user_subscription

      - name: user_transactly_vendor_opt_out
        identifier: user_transactly_vendor_opt_out

  - name: mls
    description: "mls data sources"
    database: airbyte
    schema: postgresql
    tables:
      - name: ags
        identifier: ags

      - name: listings
        identifier: listings

      - name: ofs
        identifier: ofs

  - name: hs
    description: "hubspot data sources"
    database: hubspot
    schema: v2_daily
    tables:
      - name: object_properties
        identifier: object_properties

      - name: owners
        identifier: owners

  - name: Sugar
    description: "SugarCRM data sources"
    database: Skyvia
    schema: sugarcrm
    tables:
      - name: accounts
        identifier: '"Accounts"'

      - name: contacts
        identifier: '"Contacts"'

      - name: opportunities
        identifier: '"Opportunities"'

      - name: rc360_referrer
        identifier: '"RC360_Referrer"'

      - name: revenuelineitems
        identifier: '"RevenueLineItems"'

  - name: sf
    description: "Salesforce data sources"
    database: fivetran
    schema: salesforce
    tables:
      - name: account
        identifier: account

      - name: contact
        identifier: contact

      - name: lead
        identifier: lead

      - name: opportunity
        identifier: opportunity

      - name: opportunity_line_item
        identifier: opportunity_line_item

      - name: partner_lead_c
        identifier: partner_lead_c

      - name: partner_payout_c
        identifier: partner_payout_c

      - name: product_2
        identifier: product_2

      - name: user
        identifier: user

      - name: vendor_payout_c
        identifier: vendor_payout_c