
name: 'dbtTC'
version: '1.0.0'
config-version: 2


# This setting configures which "profile" dbt uses for this project.
profile: 'dbtTC'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbtTC:
    +materialized: view
    dim:
      +materialized: table
    working:
      +materialized: ephemeral
    fact:
      +materialized: table
    GCP:
      +materialized: table


vars:
  salesforce_database: fivetran
  salesforce_schema: salesforce
  salesforce__event_enabled: false # Disable if you do not have the event table
  salesforce__task_enabled: false # Disable if you do not have the task table
  salesforce__order_enabled: false # Disable if you do not have the order table
  salesforce__user_role_enabled: false # Disable if you do not have the order table
