-- fact_line_item

create or replace table data_warehouse.fact_line_item (
    address string
    ,state string
    ,description string
    ,status string
    ,agent_pays_amt numeric
    ,office_pays_amt numeric
    ,assigned_tc_id string
    ,assigned_tc_name string
    ,order_type string
    ,order_side string
    ,order_id string
    ,transaction_id string
    ,paid string
    ,pays_at_title string
    ,tc_paid string
    ,client_id string
    ,client_fullname string
    ,client_brokerage string
    ,client_brokerage_id int
    ,tier_1_date datetime
    ,tier_2_date datetime
    ,tier_3_date date
    ,created_date date
    ,due_date datetime
    ,closing_date date
    ,cancelled_date date
    ,last_order_placed_date date
    ,last_order_due_date datetime
    ,first_order_placed_date date
    ,first_order_closed_date date
    ,fifth_order_closed_date date
    ,office_name string
    ,office_id int
    ,order_status string
    ,last_sync datetime
    ,subscription_level string
    ,transaction_coordinator_status string
    ,eligible_for_clients string
    ,hs_start_date date
    ,days_between_start_date_and_first_order_date int
    ,total_fees numeric
    ,city string
    ,status_changed_date date
    ,second_order_closed_date date
    ,third_order_closed_date date
    ,fourth_order_closed_date date
    ,contact_owner string
    ,placed_sequence int
    ,closed_sequence int
    ,original_sales_rep_name string
    ,line_item_id int
    ,stripe_paid numeric
    ,rev_share_amount numeric
    ,agreement_type string
    ,stripe_paid_date date
    ,referral_amount int
    ,user_email string
    ,user_total_closed_orders int
    ,HS_lead_status string
    ,HS_assigned_TC string
    ,assigned_tc_email string
)